version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram_bot
    restart: always
    env_file: 
      - .env
    volumes:
      - .:/app
    command: python main.py
